apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-simple-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: mendhak/http-https-echo
        ports:
        - containerPort: 80